version: '3'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      bash -c "python src/manage.py test main"
    environment:
      - POSTGRES_DATABASE_NAME=kinopoisk
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DEBUG=True
    depends_on:
        - db

  db:
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_DB=kinopoisk
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker-init:/docker-entrypoint-initdb.d/