version: '3'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DATABASE_NAME=kinopoisk
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    ports:
      - "3000:8000"

  db:
    image: postgres:11.1-alpine
    container_name: db
    environment:
      - POSTGRES_DB=kinopoisk
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/


volumes:
  db_data:
